name: InstantBreak
main: kvetinac97\Main
api: [1.13.0]
load: STARTUP
description: Tap and break!
version: 2.2.0
author: kvetinac97

commands:
  ib-on:
    description: Enable InstantBreak
    usage: "/ib-on <player>"
    permission: ib.command.on
  ib-off:
    description: Disabled InstantBreak
    usage: "/ib-off <player>"
    permission: ib.command.off

permissions:
  ib: 
   default: op
   description: "Top InstantBreak permission node"
   children:
    ib.command:
     default: op
     description: "Allow all InstantBreak commands"
     children:
      ib.command.on:
       default: op
       description: "Can enable InstantBreak for yourself"
      ib.command.off:
       default: op
       description: "Can disable InstantBreak for yourself"
    ib.other:
     default: op
     description: "Allow all InstantBreak commands for other players"
     children:
      ib.other.on:
       default: op
       description: "Allow enable InstantBreak for other players"
      ib.other.off:
       default: op
       description: "Allow disable InstantBreak for other players"
     ib.use:
       default: op
       description: "Can use InstantBreak"
       children:
        ib.use.touch:
         default: op
         description: "Can break blocks with touch"
        ib.use.silktouch:
         default: op 
         description: "Can break blocks with silktouch"
     ib.unbreakable:
       default: op
       description: "Can break unbreakable blocks (like bedrock)" 
