name: InstantBreak
main: kvetinac97\Main
api: [1.12.0]
load: STARTUP
description: Tap and break!
version: 3.0.0
author: kvetinac97

commands:
  ib:
    description: Main InstantBreak Command
    usage: "/ib <on|off> <mode> <player>"
    permission: ib.command
  ib-on:
    description: Enable InstantBreak
    usage: "/ib-on <mode> <player>"
    permission: ib.command.on
  ib-off:
    description: Disable InstantBreak
    usage: "/ib-off <mode> <player>"
    permission: ib.command.off

permissions:
  ib: 
   default: op
   description: "Top InstantBreak permission node"
   children:
    ib.command:
     default: op
     description: "Allow all InstantBreak commands"
     children:
      ib.command:
       default: op
       description: "Can use InstantBreak command"
       children:
        ib.command.silktouch:
         default: op
         description: "Can enable|disable SilkTouch mode for yourself"
         children:
          ib.command.silktouch.on:
           default: op
           description: "Can enable SilkTouch mode for yourself"
          ib.command.silktouch.off:
           default: op
           description: "Can disable SilkTouch mode for yourself"
        ib.command.touch:
          default: op
          description: "Can enable|disable Touch mode for yourself"
          children:
           ib.command.touch.on:
            default: op
            description: "Can enable Touch mode for yourself"
           ib.command.touch.off:
            default: op
            description: "Can disable Touch mode for yourself"
        ib.command.custom:
          default: op
          description: "Can enable|disable Custom mode for yourself"
          children:
           ib.command.custom.on:
            default: op
            description: "Can enable Custom mode for yourself"
           ib.command.custom.off:
            default: op
            description: "Can disable Custom mode for yourself"

    ib.other:
     default: op
     description: "Allow all InstantBreak commands for other players"
     children:
      ib.other.on:
       default: op
       description: "Allow enable InstantBreak for other players"
       children:
        ib.other.on.silktouch:
         default: op

      ib.other.off:
       default: op
       description: "Allow disable InstantBreak for other players"
     ib.use:
       default: op
       description: "Can use InstantBreak"
       children:
        ib.use.touch:
         default: op
         description: "Can break blocks with touch"
        ib.use.silktouch:
         default: op 
         description: "Can break blocks with silktouch"
     ib.unbreakable:
       default: op
       description: "Can break unbreakable blocks (like bedrock)" 
